#!/bin/bash

echo ""
echo "=== To enable/disable the Optical Links ============================="
echo "====================================================================="
echo "== sudo -u rpcpro -H /bin/bash -l                                  =="
echo "== emacs -nw bin/config/enableLinks.xml                            =="
echo "== cd ~/bin                                                        =="
echo "== ./EnableLinks                                                   =="
echo "== At the end a list of all links disabled in the DB is printed    =="
echo "== out to ~rpcpro/bin/out/disabledOptLinks.txt file.               =="
echo "==                                                                 =="
echo "====================================================================="
echo "==                                                                 =="
echo "== alternative method to login as rpcpro is to launch              =="
echo "== source /nfshome0/kbunkow/bin/xrpcpro.sh                         =="
echo "== or                                                              =="
echo "== source /nfshome0/kbunkow/bin/rpcpro.sh                          =="
echo "====================================================================="
echo ""
echo "=== To configure the Trigger ========================================"
echo "====================================================================="
echo "== login to pcrpct05 and edit a xml file:                          =="
echo "==                                                                 =="
echo "== ssh pcrpct05                                                    =="
echo "== sudo emacs /opt/xdaq/share/l1ts/profile/rpct-supervisor.xhannel =="
echo "==                                                                 =="
echo "== then you have to restart the TS cell:                           =="
echo "==                                                                 =="
echo "== sudo /sbin/service triggerd restart rpct-supervisor             =="
echo "====================================================================="
echo ""
echo "== documentation ===================================================="
echo "== https://twiki.cern.ch/twiki/bin/viewauth/CMS/TC_Control_panel   =="
echo "== https://twiki.cern.ch/twiki/bin/view/CMS/EnableOptLinks         =="
echo "====================================================================="

