#!bin/bash

echo "=== To restart the workers ========================"
echo "==================================================="
echo "== 1) Log in as rpcdev                           =="
echo "== sudo -u rpcdev -H /bin/bash -l                =="
echo "==                                               =="
echo "==--Alternative----------------------------------=="
echo "== execute: rpcdev.sh                            =="
echo "== or /nfshome0/kbunkow/bin/rpcdev.sh            =="
echo "== or just write this command:                   =="
echo "== sudo -u rpcdev -H /bin/bash -l                =="
echo "==-----------------------------------------------=="
echo "==                                               =="
echo "== 2) and go: cd bin/                            =="
echo "==                                               =="
echo "== command: rpct_xdaq                            =="
echo "== example: rpct_xdaq restart RB-1_near          =="
echo "== example: rpct_xdaq restart RB-1_far           =="
echo "== example: rpct_xdaq restart YE-3_near          =="
echo "== example: rpct_xdaq restart YE-3_far           =="
echo "==                                               =="
echo "==   help:  rpct_xdaq                            ==" 
echo "==                                               =="
echo "==-----------------------------------------------=="
echo "== if you lost the rpcdev.sh script              =="
echo "== have a look at                                =="
echo "== /nfshome0/kbunkow/bin                         =="
echo "== or check the Watchdog                         =="
echo "== http://l1page.cms/main/Watchdog               =="
echo "== or navigate to                                =="
echo "== file:///cmsnfshome0/nfshome0/rpcdev/help.html =="
echo "== with your browser or try to find this file    =="
echo "==================================================="

