#!/bin/bash

echo ""
echo ""
echo "-------------------------------------------------------------------"
echo "login to srv-c2c03-10 :: ssh srv-c2c03-10"
echo "go to directory /rpctdata/LBNoise :: "
echo "   ls -lrth /rpcpacdata/MonitorHistos  --> list files & directories"
echo "   crontab -l                          --> list running scripts"
echo "-------------------------------------------------------------------"
echo ""
echo ""
echo "-------------------------------------------------------------------"
echo "[pugliese@srv-C2C03-10 ~]$ crontab -l"
echo " 0  9 * * * /rpctdata/CAF/noiseAuto.sh"
echo " 0 14 * * * /rpctdata/CAF/noiseAuto.sh"
echo " 0 22 * * * /rpctdata/CAF/noiseAuto.sh"
echo "02 19 * * * /rpctdata/CAF/resubmitLastRuns.sh"
echo "#8 17 * * * /rpctdata/CAF/DeadStripsStudy/submitall_005_avg.sh"
echo "11 11 * * * /rpctdata/CAF/DQM_Efficiency/dqmAuto.csh 2> /rpctdata/CAF/DQM_Efficiency/erlog.log"
echo "10 18 * * * /rpctdata/CAF/DQM_Efficiency/dqmAuto.csh 2> /rpctdata/CAF/DQM_Efficiency/erlog.log"
echo "-------------------------------------------------------------------"
echo ""
echo ""
echo "----- Summary -----------------------------------------------------"
echo "--- SCRIPTS     ---   ---   ---   ---   ---   ---   ---   ---   ---"
echo "- noiseAuto.sh                                                    -"
echo "-      |--> getNextRunRange.py                                    -"
echo "-      |--> noiseDataChain.py                                     -"
echo "--- CODE  ---   ---   ---   ---   ---   ---   ---   ---   ---   ---"
echo "- ls -lrth /rpctdata/CAF/code/NoiseExe                            -"
echo "--- LB Histograms:    ---   ---   ---   ---   ---   ---   ---   ---"
echo "- ls -lrth /rpctdata/LBMonitorHistos/                             -"
echo "-------------------------------------------------------------------"
echo ""
echo ""

